### ISSUE TITLE
Docker: ModuleNotFoundError: No module named 'cyborgback`

### ISSUE THREAD

**Issue by mygithubthrowaway** [GaetanF/cyborgbackup#14]
as title, i have this exception whit docker-compose up command

**Comment by GaetanF** [comment]
I have updated the Dockerfile and the install instructions using Docker-compose in the master and develop branch.

Could you check if it's working now from our side ?

**Comment by mygithubthrowaway** [comment]
Nope, unfortunately same error:

https://pastebin.com/jgGsJYTr

**Comment by GaetanF** [comment]
I have push again the docker image to the hub.

Could you try again with pulling the new image ?

**Comment by mygithubthrowaway** [comment]
Ok now works well! 

But what are the default login on web ui?

**Comment by GaetanF** [comment]
Great !

I have updated the documentation to initiate the database of CyBorgBackup.

You need to enter the following commands : 
```
$ docker-compose exec web /bin/bash
web$ python3 /cyborgbackup/manage.py loaddata settings
web$ echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin@cyborg.local', 'admin')" | python3 /cyborgbackup/manage.py shell
web$ exit
```

**Comment by mygithubthrowaway** [comment]
Perfect! work as expected
